### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by wyatt-wong** [dfgordon/Realm#2]
Please provide the build instructions

**Comment by dfgordon** [comment]
Can you see the wiki page https://github.com/dfgordon/Realm/wiki/Deployment and let me know if it addresses your issue?

**Comment by wyatt-wong** [comment]
> Can you see the wiki page https://github.com/dfgordon/Realm/wiki/Deployment and let me know if it addresses your issue?

I was wondering how to create the 4 .DO files in Virtual ][ and where do I save those 4 .DO files ?

**Comment by wyatt-wong** [comment]
The deploy-all-dos33.scpt is under the "Realm/scripts" sub-folder.

**Comment by wyatt-wong** [comment]
After executed deploy-all-dos33.scpt and select "clean" or "binaries" function, I got the following error.

<img width="812" alt="Screen Shot 2021-10-02 at 10 46 46 AM" src="https://user-images.githubusercontent.com/10095648/135701434-6eb30343-5e59-4527-bd3a-c751f5fd22bb.png">

**Comment by dfgordon** [comment]
I get the same error if I use the ~ character.  Try editing the realm_path assignment so it reads

set realm_path to "/Users/your_username/Documents/appleii/Realm/"

where your_username must be changed to whatever your user folder is called.  To put it another way, set realm_path to the full path of the project folder.

I am assuming this is the latest script, but earlier ones should behave similarly.

**Comment by dfgordon** [comment]
Regarding the .DO files, I created them using CiderPress on a Windows computer and then copied them over to the Mac.  You can also use the images from any release if that is easier.  Simply change the filenames and clean out the old files (either manually or let the script do it for you).

**Comment by wyatt-wong** [comment]
> I get the same error if I use the ~ character. Try editing the realm_path assignment so it reads
> 
> set realm_path to "/Users/your_username/Documents/appleii/Realm/"
> 
> where your_username must be changed to whatever your user folder is called. To put it another way, set realm_path to the full path of the project folder.
> 
> I am assuming this is the latest script, but earlier ones should behave similarly.

I spent around 30 minutes research and found out how to fix the "~" issue but I spent about an hour and realized I don't have permission to push the update back to your GitHub repository. Anyway, here is the changes:

Location: https://github.com/dfgordon/Realm/blob/main/scripts/deploy-all-dos33.scpt

-- set realm_path to "/Users/dan/Documents/appleii/Realm/"

set home_folder to path to home folder
set home_path to POSIX path of home_folder
set realm_path to home_path & "Documents/appleii/Realm/"

**Comment by wyatt-wong** [comment]
> Regarding the .DO files, I created them using CiderPress on a Windows computer and then copied them over to the Mac. You can also use the images from any release if that is easier. Simply change the filenames and clean out the old files (either manually or let the script do it for you).

When you need to use both Windows and macOS in order to successfully build the binaries from the source, it is regarded as a failure in my view. A good build instruction should be available to perform in either Windows or macOS.

Anyway, I haven't time to explore the rest of your build instructions but at least I resolved the issue of the "~" path. I will resume reading your remaining instructions and hope I could understand and successfully learnt how to build the binaries from source in 1-week's time (hopefully).

**Comment by dfgordon** [comment]
I put your home path modification into my local version, it appears to work, thanks.

You don't need Windows, but I'm sorry for the frustration in any case.  What I will do is include the starting images in the project tree.  That should solve it.

Eventually I have in mind to replace the workflow of Virtual ][ with more efficient command line tools, pending availability.  We have the tokenizer thanks to https://github.com/KrisKennaway/bastoken, but for disk images it seems we only have AppleCommander, which would bring Java in.

**Comment by dfgordon** [comment]
Perhaps I should say - just in case of misunderstanding - if all someone wants to do is play Realm, you don't need to do any of this.  You just download the release.

**Comment by wyatt-wong** [comment]
> Perhaps I should say - just in case of misunderstanding - if all someone wants to do is play Realm, you don't need to do any of this. You just download the release.

Of course. That's what I do before. But still people have the rights to build it from source for any GitHub projects. 

I built 4am passport, Total Replay (4cade), Total Replay II (4sports) after realizing 4am is a busy (or lazy) guy who did not always provide the latest binaries releases in his GitHub projects and I built them in my macOS and uploaded to the Apple II Enthusiasts facebook group for the benefits of other Apple II Fans.

Anyway, you might have to update the changes of "deploy-all-dos33.scpt" back to your GitHub repository and possibly acknowledge for my fix.

**Comment by wyatt-wong** [comment]
I was able to compile into DOS version, after following your deployment steps on DOS 3.3. On top of that, I also found out how to revise the realm_path variable to make it less dependent on the macOS username). I ran into some issues in the ProDOS deployment and are now stuck in the "Monsters" part.

However, on second thought, you could run the script in ONE single batch without user to select "each" of the steps one by one. That would save much time.. Although I still disagree that your deployment step is to simply insert the code into the 4 disk files using Virtual ][. I  would expect to see the assembly source code files in this page instead of just a bunch of hex codes.

**Comment by dfgordon** [comment]
Before I respond any further can you please review https://docs.github.com/en/github/site-policy/github-community-guidelines.  When you called my process a "failure" I let it go, but now you accused 4am of being "a busy (or lazy) guy", and it begins to look like this sort of tone is a pattern.  If that is the case we cannot work together.

**Comment by wyatt-wong** [comment]
> Before I respond any further can you please review https://docs.github.com/en/github/site-policy/github-community-guidelines. When you called my process a "failure" I let it go, but now you accused 4am of being "a busy (or lazy) guy", and it begins to look like this sort of tone is a pattern. If that is the case we cannot work together.

In that case, I apologised of what I said before. I guessed you can review your deployment process and I hope someone else can make use of it.
